### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Freddy50309** [SistemasTecTlaxiaco/infografia-Freddy50309#1]
Se realiza una infografía acerca de la realidad aumentada y realidad virtual con sus descripciones, características, funciones y aplicaciones.

![Infografia_Freddy](https://user-images.githubusercontent.com/64513432/110068228-dcbed080-7d3a-11eb-8d32-f74961b70fd5.jpg)

**Comment by hiuta** [comment]
Calificacion 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
